server:
  port: 8080

spring:
  application:
    name: bff-azure-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          # Tenant issuer (v2.0)
          issuer-uri: https://login.microsoftonline.com/ba56039b-5f8d-4ed6-9375-45ff34bb5a71/v2.0

logging:
  level:
    org.springframework.security: INFO
    com.example.bffazure: DEBUG
